server {
    listen 80;
    server_name api.gopikrishnanrmg.ca;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.gopikrishnanrmg.ca;

    ssl_certificate /etc/nginx/ssl/origin.pem;
    ssl_certificate_key /etc/nginx/ssl/origin.key;

    location / {
        proxy_pass http://api-gateway:8887;
    }
}

server {
    listen 80;
    server_name grafana.gopikrishnanrmg.ca;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name grafana.gopikrishnanrmg.ca;

    ssl_certificate /etc/nginx/ssl/origin.pem;
    ssl_certificate_key /etc/nginx/ssl/origin.key;

    location / {
        proxy_pass http://grafana:3000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header CF-Connecting-IP $http_cf_connecting_ip;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

server {
    listen 80;
    server_name mcp.gopikrishnanrmg.ca;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name mcp.gopikrishnanrmg.ca;

    ssl_certificate /etc/nginx/ssl/origin.pem;
    ssl_certificate_key /etc/nginx/ssl/origin.key;

    location / {
        proxy_pass http://mcp-server:8884;
    }
}

server {
    listen 80;
    server_name s3.gopikrishnanrmg.ca;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name s3.gopikrishnanrmg.ca;

    ssl_certificate /etc/nginx/ssl/origin.pem;
    ssl_certificate_key /etc/nginx/ssl/origin.key;

    location / {
        proxy_pass http://minio:9000;

        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_buffering off;
        proxy_request_buffering off;

        chunked_transfer_encoding off;
    }
}

server {
    listen 80;
    server_name s3web.gopikrishnanrmg.ca;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name s3web.gopikrishnanrmg.ca;

    ssl_certificate /etc/nginx/ssl/origin.pem;
    ssl_certificate_key /etc/nginx/ssl/origin.key;

    location / {
        proxy_pass http://minio:9001;
    }
}
