"""add openai_conversation_id

Revision ID: 8c50c1697d85
Revises: d0125b8f9b3c
Create Date: 2026-01-25 17:20:21.099247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c50c1697d85'
down_revision: Union[str, Sequence[str], None] = 'd0125b8f9b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('openai_conversation_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'openai_conversation_id')
    # ### end Alembic commands ###
