#!/bin/bash

sudo dnf update -y

sudo dnf install -y awscli git docker

sudo systemctl enable --now docker

sudo usermod -aG docker ec2-user

sudo curl -SL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-aarch64 -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo mkdir -p /usr/libexec/docker/cli-plugins
sudo ln -s /usr/local/bin/docker-compose /usr/libexec/docker/cli-plugins/docker-compose || true

sudo mkdir -p /etc/nginx/ssl
sudo mkdir -p /opt/portfolio
cd /opt/portfolio

sudo aws s3 cp s3://artifacts-portfolio-1996/nginx.conf nginx.conf
sudo aws s3 cp s3://artifacts-portfolio-1996/docker-compose.yml docker-compose.yml
sudo aws s3 cp s3://artifacts-portfolio-1996/.env .env
sudo aws s3 cp s3://artifacts-portfolio-1996/prometheus.yml prometheus.yml
sudo aws s3 cp s3://artifacts-portfolio-1996/alerts.yml alerts.yml
sudo aws s3 cp s3://artifacts-portfolio-1996/origin.key /etc/nginx/ssl/origin.key
sudo aws s3 cp s3://artifacts-portfolio-1996/origin.pem /etc/nginx/ssl/origin.pem
sudo aws s3 cp s3://artifacts-portfolio-1996/init-multiple-dbs.sql init-multiple-dbs.sql

sudo mkdir -p postgres-data mongo-data redis-data rabbitmq_data rabbitmq_logs minio-data grafana-data data
sudo chmod 600 /etc/nginx/ssl/origin.key
sudo chmod 644 /etc/nginx/ssl/origin.pem
sudo chmod -R 777 /opt/portfolio

sudo docker compose --profile infra --profile services up -d
