name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["dev", "main"]
  workflow_dispatch:
  
jobs:
  backend-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway, portfolio-service, config-server, analytics-server]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Run tests
        run: |
          cd backend/${{ matrix.service }}
          ./mvnw test

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install deps
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

